export const TOP_TRENDING_LIST = [
  {
    id: 1,
    name: "Form Chair Brass Base",
    url: process.env.PUBLIC_URL + "./bg.png",
    price: 569,
    price_discount: 0,
    isPreorder: 0,
  },
  {
    id: 2,
    name: "Vase Echasse Large",
    url: process.env.PUBLIC_URL + "./bg-1.png",
    price: 569,
    price_discount: 156,
    isPreorder: 1,
  },
  {
    id: 3,
    name: "Form Chair Brass Base",
    url: process.env.PUBLIC_URL + "./bg-2.png",
    price: 569,
    price_discount: 0,
    isPreorder: 0,
  },
  {
    id: 4,
    name: "Bottle Grinder Of Pepper",
    url: process.env.PUBLIC_URL + "./bg-3.png",
    price: 569,
    price_discount: 0,
    isPreorder: 0,
  },
  {
    id: 5,
    name: "Form Bar Stool Oak Base",
    url: process.env.PUBLIC_URL + "./bg-4.png",
    price: 569,
    price_discount: 0,
    isPreorder: 0,
  },
  {
    id: 6,
    name: "Table Lamp 15x29cm",
    url: process.env.PUBLIC_URL + "./bg-5.png",
    price: 569,
    price_discount: 0,
    isPreorder: 0,
  },
  {
    id: 7,
    name: "Carrie Table Lamp",
    url: process.env.PUBLIC_URL + "./bg-1.png",
    price: 569,
    price_discount: 0,
    isPreorder: 0,
  },
  {
    id: 8,
    name: "Form Armchair Black",
    url: process.env.PUBLIC_URL + "./bg-6.png",
    price: 569,
    price_discount: 156,
    isPreorder: 1,
  },
];
